services:
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/booker_db

    volumes:
      - .:/app
    command: npm start

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: booker_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
